version: '3'
services:
    back:
        image: "node:10.21.0"
        working_dir: /home/node/app
        volumes:
        - ./:/home/node/app
        command: "npm run test:ci:docker"
        env_file:
        - ./.env
        ports:
        - ${PORT}:${PORT}