version: 2
jobs:
    test:
        docker:
            - image: circleci/node:10
        environment:
            - jwt_secret: s3cr3t_of_doom
            - PORT: 1337
            - fronturl: https//fronturl.com
            - oauth_discord_base_url: http://localhost:1664
        steps:
            - run:
                name: versions
                command: |
                  node --version
                  npm --version
            - checkout
            - run:
                name: Install dependencies
                command: npm install
            - run:
                name: Lint
                command: npm run lint
            - run:
                name: Set env
                command: npm run preset:env
                environment:
                - NODE_ENV: production
            - run:
                name: Start Server
                command: npm run start:daemon
                
            - run:
                name: Test
                command: npm test
workflows:
    version: 2
    test:
        jobs:
            - test
