version: 2
jobs:
    build-test:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - run:
                name: Install dependencies
                command: npm install
            - run:
                name: Lint
                command: npm run lint
            - run:
                name: Set env
                command: npm run preset:env
            - run:
                name: Start Server
                command: npm run start:daemon
                environment:
                - NODE_ENV: production
                - jwt_secret: s3cr3t_of_doom
                - PORT: 1337
            - run:
                name: Test
                command: npm test
                environment:
                - NODE_ENV: production
                - jwt_secret: s3cr3t_of_doom
                - PORT: 1337
workflows:
    version: 2
    build-deploy:
        jobs:
            - build-test
