on: [push, pull_request]
name: Lint
jobs:
  standardjs:
    name: StandardJs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: StandardJs
      uses: docker://jopereyral/standardjs-action
      with:
        args: --fix